# -*- coding: utf-8 -*-
import re
from odoo import api, fields, models, _
from odoo.exceptions import UserError
from markupsafe import Markup

from html.parser import HTMLParser
import html
from odoo.tools import html_escape

class ChatterHTMLParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.reset()
        self.fed = []
        self.ignored_depth = 0

    def handle_starttag(self, tag, attrs):
        if tag in ('style', 'script', 'head'):
            self.ignored_depth += 1
        elif tag in ('p', 'br', 'div', 'tr', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'):
            if self.ignored_depth == 0:
                self.fed.append('\n')
        elif tag == 'td':
            if self.ignored_depth == 0:
                self.fed.append(' ')

    def handle_endtag(self, tag):
        if tag in ('style', 'script', 'head'):
            self.ignored_depth = max(0, self.ignored_depth - 1)
        elif tag in ('p', 'div', 'tr'):
            if self.ignored_depth == 0:
                self.fed.append('\n')

    def handle_data(self, d):
        if self.ignored_depth == 0:
            self.fed.append(d)

    def get_data(self):
        text = ''.join(self.fed)
        text = html.unescape(text)
        text = re.sub(r'\n\s*\n+', '\n\n', text)
        return text.strip()

def clean_html_for_chatter(html_str: str) -> str:
    if not html_str:
        return ""
    # Strip basic block comments if any
    html_str = re.sub(r'<!--.*?-->', '', html_str, flags=re.DOTALL)
    parser = ChatterHTMLParser()
    parser.feed(html_str)
    plain_text = parser.get_data()
    
    # Reconstruct with clean p tags and br for spacing
    paragraphs = [p.strip() for p in plain_text.split('\n\n') if p.strip()]
    chatter_paragraphs = []
    for p in paragraphs:
        formatted_p = html_escape(p).replace('\n', '<br/>')
        chatter_paragraphs.append(f"<p>{formatted_p}</p>")
    return "\n".join(chatter_paragraphs)

class ResPartner(models.Model):
    _inherit = 'res.partner'

    x_lisa_wb_email_html = fields.Html(
        string='Lisa Win-Back Email HTML',
        help="Holds the draft email content generated by Lisa AI agent.",
        copy=False
    )
    x_lisa_wb_email_subject = fields.Char(
        string='Lisa Win-Back Email Subject',
        help="Holds the exact generated subject used by the Lisa AI win-back mail template.",
        copy=False
    )
    lisa_wb_processed = fields.Boolean(
        string='Lisa Win-Back Processed',
        default=False,
        help="Indicates if the Lisa agent has already completed the win-back campaign outreach for this partner.",
        copy=False
    )

    def action_send_lisa_winback(self):
        """Manually triggers sending the Lisa Win-Back Campaign Outreach mail template."""
        self.ensure_one()
        
        if self.lisa_wb_processed:
            raise UserError(_("The win-back outreach has already been completed for this partner."))

        rec_html = self.x_lisa_wb_email_html
        if not rec_html:
            raise UserError(_("There are no Lisa win-back recommendations or emails drafted for this Customer. Please wait for the agent to process it first."))

        # Find the mail template
        template = self.env['mail.template'].search([
            ('name', '=', 'Lisa Win-Back Campaign Outreach')
        ], limit=1)
        if not template:
            template = self.env.ref('Win_Back_Agent_odoo.lisa_winback_campaign_outreach_template', raise_if_not_found=False)
            
        if not template:
            raise UserError(_("Mail Template 'Lisa Win-Back Campaign Outreach' not found. Please run the setup script or configure it."))

        # Route directly to override email to protect real customers if configured
        company = self.env.company
        recipient_override = company.lisa_wb_recipient_override
        email_values = {}
        if recipient_override:
            email_values.update({
                'email_to': recipient_override,
                'partner_ids': [(6, 0, [])],
                'recipient_ids': [(6, 0, [])]
            })
        
        # Outgoing from salesperson's email as sender
        salesperson = self.user_id
        if salesperson and salesperson.email:
            email_values['email_from'] = salesperson.email_formatted or salesperson.email
        
        # Trigger send
        template.send_mail(self.id, force_send=True, email_values=email_values)

        # Determine the stage number before updating the campaign record
        campaign = self.env['winback.campaign'].search([('partner_id', '=', self.id)], limit=1)
        current_stage = campaign.stage if campaign else 'none'
        
        stage_num = "1"
        if current_stage == 'email_1_sent':
            stage_num = "2"
        elif current_stage == 'email_2_sent':
            stage_num = "3"

        # Create or update winback.campaign record
        if not campaign:
            self.env['winback.campaign'].create({
                'partner_id': self.id,
                'stage': 'email_1_sent',
                'status': 'active',
                'email_1_sent_date': fields.Datetime.now()
            })
        else:
            if campaign.stage == 'none':
                campaign.write({
                    'stage': 'email_1_sent',
                    'status': 'active',
                    'email_1_sent_date': fields.Datetime.now()
                })
            elif campaign.stage == 'email_1_sent':
                campaign.write({
                    'stage': 'email_2_sent',
                    'status': 'active',
                    'email_2_sent_date': fields.Datetime.now()
                })
            elif campaign.stage == 'email_2_sent':
                campaign.write({
                    'stage': 'email_3_sent',
                    'status': 'active',
                    'email_3_sent_date': fields.Datetime.now()
                })

        # Mark lead as processed
        self.write({
            'lisa_wb_processed': True
        })

        # Log confirmation note to chatter (disabled to prevent duplicate/second email from being posted)
        # subject = self.x_lisa_wb_email_subject or template.subject or ''
        # subject = re.sub(r'{{\s*object\.name\s*}}', self.name or '', subject, flags=re.IGNORECASE)
        # 
        # recipient_email = self.email or ''
        # header_html = (
        #     f"<b>Win-Back Email {stage_num} Sent</b><br/>"
        #     f"<b>To:</b> {html_escape(recipient_email)}<br/>"
        #     f"<b>Subject:</b> {html_escape(subject)}<br/><br/>"
        # )
        # chatter_body = Markup(header_html) + Markup(clean_html_for_chatter(rec_html))
        # self.message_post(body=chatter_body)

        return True

    def message_post(self, **kwargs):
        res = super(ResPartner, self).message_post(**kwargs)
        message_type = kwargs.get('message_type')
        # Only fire for genuine inbound emails from external senders
        if message_type == 'email':
            author_id = kwargs.get('author_id')
            # Skip if author is an internal Odoo user (not a customer)
            if not author_id:
                campaign = self.env['winback.campaign'].search([
                    ('partner_id', '=', self.id),
                    ('stage', 'not in', ['replied', 'reactivated', 'cold'])
                ], limit=1)
                if campaign:
                    campaign.write({'stage': 'replied', 'status': 'completed'})
                    # Create To-Do activity for the salesperson
                    if self.user_id:
                        self.env['mail.activity'].create({
                            'res_model_id': self.env['ir.model']._get('res.partner').id,
                            'res_id': self.id,
                            'activity_type_id': self.env.ref('mail.mail_activity_data_todo').id,
                            'summary': 'Win-Back Campaign - Customer Replied',
                            'note': 'The customer has replied to the win-back campaign email. Please review the customer chatter and follow up.',
                            'user_id': self.user_id.id,
                            'date_deadline': fields.Date.context_today(self)
                        })
        return res

    def action_view_winback_campaign(self):
        self.ensure_one()
        campaign = self.env['winback.campaign'].search([('partner_id', '=', self.id)], limit=1)
        action = self.env["ir.actions.actions"]._for_xml_id("Win_Back_Agent_odoo.action_winback_campaign")
        if campaign:
            action.update({
                'res_id': campaign.id,
                'view_mode': 'form',
                'views': [(False, 'form')],
            })
        else:
            action.update({
                'view_mode': 'form',
                'views': [(False, 'form')],
                'context': {'default_partner_id': self.id},
            })
        return action
